title: My Personal Website
baseURL: https://anthony-pignatelli.github.io
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Home
    weight: 1
  #fr:
    #contentDir: content/fr
    #title: Anthony Pignatelli Fr
    #weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  ananke_socials:
    - name: Dallas Lab
      url: https://taddallas.github.io
    - name: github
      url: https://github.com/anthony-pignatelli
  author: ''
  background_color_class: bg-dark-blue
  description: The last theme you'll ever need. Maybe.
  favicon: ''
  site_logo: ''
  text_color: 'black'

