---
title: "Teaching"
---

## Current Courses

-   BIOL 301 Ecology and Evolution Lecture (Jan 2026-Present)

    -   Course Description: Concepts of evolution, populations, and population interactions; communities and ecosystems.

## Past Courses

-   BIOL 102L Biological Principles II Laboratory (Aug-Dec 2023)

    -   Course Description: Experimental examination of structure and function of plant and animal systems, biodiversity, ecology.

-   BIOL 301L Ecology and Evolution Laboratory (Jan 2024-May 2025)

    -   Course Description: Experiments, exercises, and demonstrations.

## Educational Training

I have been taking advantage of programs and short courses offered through the University of South Carolina [Center for Teaching Excellence](https://sc.edu/about/offices_and_divisions/cte/index.php) as well as courses offered through the Department of Biological Sciences.

-   [Preparing Future Faculty Program](https://sc.edu/about/offices_and_divisions/cte/graduate_teaching_assistants/preparing_future_faculty/) - December 2025-Present

    -   The Preparing Future Faculty (PFF) program is a professional development opportunity that provides assistance to graduate students and post-docs who want to become faculty members at the college level. PFF is a national program established by the Council of Graduate Schools, the Association of American Colleges and Universities, the Pew Charitable Trust and the National Science Foundation.

-   [Foster Student Learning through Effective Teaching - Short Course](https://sc.edu/about/offices_and_divisions/cte/programs/short_courses/effective_teaching/) - Jan 2026 - Feb 2026

    -   Enhance teaching practices using evidence-based strategies and tools. Learning how to:

        -   Design effective, inclusive courses

        -   Communicate expectations clearly

        -   Create engaging and supportive learning environments

-   BIOL 710: Scientific Teaching and Pedagogy Course - Aug 2025-Dec 2025

    -   Course Description: This course is designed to increase teaching proficiency on the science behind student learning, scientific teaching, assessments and rubrics, active learning, project-based learning, teaching technology, inclusive teaching and universal design, classroom and course management, and course design. Participants will begin to develop their own set of course content (specific to their area of expertise) and will deliver that course content as the designated instructor of record after completion of this course. Students will also develop a proper syllabus for their designated course and prepare their own teaching philosophy at the end of this course.

# 
